language: scala

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

scala:
  - 2.11.6

jdk:
  - oraclejdk8

script:
  - sbt test package

notifications:
  email:
    - pricingtool@autoscout24.com