language: scala

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"

scala:
- 2.11.6

jdk:
- oraclejdk8

script:
- sbt test package
# Trick to avoid unnecessary cache updates
- find $HOME/.sbt -name "*.lock" | xargs rm

notifications:
  email:
  - pricingtool@autoscout24.com
  slack:
    rooms:
      - as24-tatsu:XJHB0uxN45HgTE4yZil25oQS
    on_success: change
    on_failure: always

deploy:
  provider: releases
  api_key: $GITHUB_APIKEY
  file: target/scala-2.11/featurebee_2.11-1.$TRAVIS_BUILD_NUMBER.jar
  skip_cleanup: true
  on:
    tags: true
    repo: AutoScout24/featurebee-scala