language: scala

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"

scala:
- 2.11.6

jdk:
- oraclejdk8

script:
- sbt test package
# Trick to avoid unnecessary cache updates
- find $HOME/.sbt -name "*.lock" | xargs rm

notifications:
  email:
  - pricingtool@autoscout24.com
  slack:
    rooms:
      - as24-tatsu:XJHB0uxN45HgTE4yZil25oQS
    on_success: change
    on_failure: always

after_success:
  - >
      sh "$TRAVIS_BUILD_DIR/.travis.credentials.sh" &&
      sbt publish